UN_BODIES = [
    "DESA",
    "Department of Economic and Social Affairs",
    "DFS",
    "Department of Field Support",
    "DGACM",
    "Department for General Assembly and Conference Management",
    "DM",
    "Department of Management",
    "DPA",
    "Department of Political Affairs",
    "DPI",
    "Department of Public Information",
    "DPKO",
    "Department of Peacekeeping Operation",
    "DSS",
    "Department of Safety and Security",
    "ECA",
    "Economic Commission for Africa",
    "ECE",
    "Economic Commission for Europe",
    "ECLAC",
    "Economic Commission for Latin America and the Caribbean",
    "ECOSOC",
    "Economic and Social Council",
    "EOSG",
    "Executive Office of the Secretary-General",
    "ESCAP",
    "Economic and Social Commission for Asia and the Pacific",
    "ESCWA",
    "Economic and Social Commission for Western Asia",
    "IAEA",
    "International Atomic Energy Agency",
    "ICAO",
    "International Civil Aviation Organization",
    "ICJ",
    "International Court of Justice",
    "IFAD",
    "International Fund for Agricultural Development",
    "ILO",
    "International Labour Organization",
    "IMF",
    "International Monetary Fund",
    "IMO",
    "International Maritime Organization",
    "IOM",
    "International Organization for Migration",
    "ITC",
    "International Trade Centre",
    "ITU",
    "International Telecommunication Union",
    "OAJ",
    "Office of the Administration of Justice",
    "OCHA",
    "Office for the Coordination of Humanitarian Affairs",
    "OHCHR",
    "Office of the United Nations High Commissioner for Human Rights",
    "OIOS",
    "Office of Internal Oversight Services",
    "OLA",
    "Office of Legal Affairs",
    "OSAA",
    "Office of the Special Adviser on Africa",
    "PBC",
    "United Nations Peacebuilding Commission",
    "PBSO",
    "Peacebuilding Support Office",
    "Secretariat",
    "Secretariat",
    "SRSG/CAAC",
    "Office of the Special Representative of the Secretary-General for Children and Armed Conflict",
    "SRSG/SVC",
    "Office of the Special Representative of the Secretary-General on Sexual Violence in Conflict",
    "SRSG/VAC",
    "Office of the Special Representative of the Secretary-General on violence against children",
    "Trusteeship Council",
    "Trusteeship Council (currently inactive)",
    "UN Women",
    "United Nations Entity for Gender Equality and the Empowerment of Women",
    "UN-Habitat",
    "United Nations Human Settlements Programme",
    "UN-OHRLLS",
    "Office of the High Representative for Least Developed Countries, Landlocked Developing Countries, "
    "and Small Island Developing States",
    "UN-WOMEN",
    "United Nations Entity for Gender Equality and the Empowerment of Women",
    "UNAIDS",
    "Joint United Nations Programme on HIV/AIDS",
    "UNCCT",
    "United Nations Counter-Terrorism Centre",
    "UNCDF",
    "United Nations Capital Development Fund",
    "UNCTAD",
    "United Nations Conference on Trade and Development",
    "UNDP",
    "United Nations Development Programme",
    "UNEP",
    "United Nations Environment Programme",
    "UNESCO Intangible Cultural Heritage Lists",
    "United Nations Educational, Scientific, and Cultural Organization Intangible Cultural Heritage Lists",
    "UNESCO",
    "United Nations Educational, Scientific, and Cultural Organization",
    "UNFCCC",
    "United Nations Framework Convention on Climate Change",
    "UNFPA",
    "United Nations Population Fund",
    "UNGA",
    "General Assembly",
    "UNGEGN",
    "United Nations Group of Experts on Geographical Names",
    "UNHCR",
    "Office of the United Nations High Commissioner for Refugees",
    "UNHCR",
    "United Nations High Commissioner for Refugees",
    "UNHRC",
    "United Nations Human Rights Council",
    "UNICEF",
    "United Nations Children Fund",
    "UNICEF",
    "United Nations Children's Fund",
    "UNICRI",
    "United Nations Interregional Crime and Justice Research Institute",
    "UNIDIR",
    "UNIDIR United Nations Institute for Disarmament Research",
    "UNIDO",
    "United Nations Industrial Development Organization",
    "UNIFEM",
    "United Nations Development Fund for Women (Now part of UN Women)",
    "UNISDR",
    "United Nations International Strategy for Disaster Reduction",
    "UNISDR",
    "United Nations Office for Disaster Risk Reduction",
    "UNITAR",
    "United Nations Institute for Training and Research",
    "UNJSPF",
    "United Nations Joint Staff Pension Fund",
    "UNODA",
    "United Nations Office for Disarmament Affairs",
    "UNODC",
    "United Nations Office on Drugs and Crime",
    "UNOG",
    "United Nations Office at Geneva",
    "UNON",
    "United Nations Office at Nairobi",
    "UNOOSA",
    "United Nations Office for Outer Space Affairs",
    "UNOP",
    "United Nations Office for Partnerships",
    "UNOPS",
    "United Nations Office for Project Services",
    "UNOSDP",
    "United Nations Office on Sport for Development and Peace",
    "UNOV",
    "United Nations Office at Vienna",
    "UNPA",
    "United Nations Postal Administration",
    "UNRISD",
    "United Nations Research Institute for Social Development",
    "UNRWA",
    "United Nations Relief and Works Agency for Palestine Refugees in the Near East",
    "UNSSC",
    "United Nations System Staff College",
    "UNU",
    "United Nations University",
    "UNV",
    "United Nations Volunteers",
    "UPU",
    "Universal Postal Union",
    "WBG",
    "World Bank Group",
    "WFP",
    "World Food Programme",
    "WHO",
    "World Health Organization",
    "WIPO",
    "World Intellectual Property Organization",
    "WMO",
    "World Meteorological Organization",
]
