version: "3"
services:
  unml-api:
    build:
      context: .
      dockerfile: docker/ml-pipeline.dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/unml-api
    depends_on:
      - neo4j
    restart: on-failure

  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ~/.unml/data:/data:rw
    environment:
      - NEO4J_AUTH=none
